### ISSUE TITLE
[BUG] - Outdated link

### ISSUE THREAD

**Issue by MHWcreations** [11TStudio/SquadStatsJSPRO#23]
**Outdated link in the *postrequisites* section**

When you click the link° given in the [*postrequisites*](https://github.com/11TStudio/SquadStatsJSPRO#postrequisites) section
you are forwarded to a discord page that displays a message, "Link expired".

It is not a very important problem, but I don't know if I can go further with configuration without the emoji server.

°Link: "...[this emoji discord server](https://discord.gg/NPkySYKMkN)..."

**Comment by 11TStudio** [comment]
I'm not going to put time for the link since it will be not used in the current version that we are building. It will be released within 1-2 days. Please bare with me and do not use the current version.
