### ISSUE TITLE
Map change dont work

### ISSUE THREAD

**Issue by CptEagle** [11TStudio/SquadStatsJSPRO#53]
**Describe the bug**
Map dont change trough panel

**To Reproduce**
Clicked on the button change map from panel, nothing happend.

dashboard > change map > no action

**Comment by 11TStudio** [comment]
This issue has been fixed in https://github.com/11TStudio/SquadStatsJSPRO/commit/21304b8c05f70c4efe4346e6da47f58604b25cca
