### ISSUE TITLE
[Feature request] - Force switch player

### ISSUE THREAD

**Issue by CptEagle** [11TStudio/SquadStatsJSPRO#54]
**Is your feature request related to a problem? Please describe.**
From the player list there is no option to force switch a player to the other side

**Describe the solution you'd like**
button to force switch player

**Comment by 11TStudio** [comment]
Done in https://github.com/11TStudio/SquadStatsJSPRO/commit/2afe64e49da20f4c0c6e6a1bedfab1730c3ff191
