### ISSUE TITLE
[Change] - Latest TPS Change the way it gathers 

### ISSUE THREAD

**Issue by 11TStudio** [11TStudio/SquadStatsJSPRO#59]
Latest TPS should be listened from SocketIO instead of taking the last data from DB.

Using `TICK_RATE`.

**Comment by CO-RONA** [comment]
👍 

Update Suggestion:

maybe adding cache (like layerHistory in SQJS) ❔
- for TPS due to in every page it starts from 0 because it waits the TICK_RATE  event happen, also for smooth and more sexy look

**Comment by 11TStudio** [comment]
> 👍
> 
> Update Suggestion:
> 
> maybe adding cache (like layerHistory in SQJS) ❔
> 
> * for TPS due to in every page it starts from 0 because it waits the TICK_RATE  event happen, also for smooth and more sexy look

Nice idea... But might be not needed since TPS comes every few seconds 👍

**Comment by 11TStudio** [comment]
Update: SocketIO is pretty fast so no need for this anymore.
