### ISSUE TITLE
Disbanding a squad.

### ISSUE THREAD

**Issue by CptEagle** [11TStudio/SquadStatsJSPRO#60]
Disband squad.

When clicking on disband squad, no action happend.

**Comment by CO-RONA** [comment]
I just tried and it worked 👇 I don't see any bug in here 😄 
![image](https://user-images.githubusercontent.com/82226864/146061806-77caec54-a307-454c-95f6-7804bcc76129.png)

**Comment by 11TStudio** [comment]
@CptEagle if you can confirm it, please close the ticket :)

**Comment by 11TStudio** [comment]
I've tested this in my own server and works just fine.
