### ISSUE TITLE
[BUG] - Expired Ban Comment doesn't work

### ISSUE THREAD

**Issue by CO-RONA** [11TStudio/SquadStatsJSPRO#63]
**Expired Ban Comment doesn't work and squad gets the ban as it's**
 I assume tha Squad don't buy `// \\` in config files so permanent bans (`:0`) remains on when the map or server re/started 

**Solution**
Removing the expired bans from /banlist/:token api so the game can't get them or adding /* *\ instead of `// \\`if'd work

**Comment by 11TStudio** [comment]
Fixed in: https://github.com/11TStudio/SquadStatsJSPRO/commit/6b6c807e4a9008da5fc286e62b5a784f5e3bf258
